//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDTUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream alarm {
            get {
                return ResourceManager.GetStream("alarm", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream attention {
            get {
                return ResourceManager.GetStream("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\BirthCert\BirthCert1524.ini.
        /// </summary>
        internal static string birth_cert {
            get {
                return ResourceManager.GetString("birth_cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\CashlessLib.log.
        /// </summary>
        internal static string cashless_log {
            get {
                return ResourceManager.GetString("cashless_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\CpuEventLog.ini.
        /// </summary>
        internal static string cpu_event_log {
            get {
                return ResourceManager.GetString("cpu_event_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\disable.png.
        /// </summary>
        internal static string disable_button {
            get {
                return ResourceManager.GetString("disable_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\DisabledGames.ini.
        /// </summary>
        internal static string disabled_games {
            get {
                return ResourceManager.GetString("disabled_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\wav\util.wav.
        /// </summary>
        internal static string door_open_sound {
            get {
                return ResourceManager.GetString("door_open_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\down.png.
        /// </summary>
        internal static string down_button {
            get {
                return ResourceManager.GetString("down_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\enable.png.
        /// </summary>
        internal static string enable_button {
            get {
                return ResourceManager.GetString("enable_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\EspLiveSettings.ini.
        /// </summary>
        internal static string esp_live_ini {
            get {
                return ResourceManager.GetString("esp_live_ini", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream exit {
            get {
                return ResourceManager.GetStream("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\exe.png.
        /// </summary>
        internal static string FILE_TYPE_EXE {
            get {
                return ResourceManager.GetString("FILE_TYPE_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\folder.png.
        /// </summary>
        internal static string FILE_TYPE_FOLDER {
            get {
                return ResourceManager.GetString("FILE_TYPE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\png.png.
        /// </summary>
        internal static string FILE_TYPE_IMG {
            get {
                return ResourceManager.GetString("FILE_TYPE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\ini.png.
        /// </summary>
        internal static string FILE_TYPE_INI {
            get {
                return ResourceManager.GetString("FILE_TYPE_INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\raw.png.
        /// </summary>
        internal static string FILE_TYPE_RAW {
            get {
                return ResourceManager.GetString("FILE_TYPE_RAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\unknown.png.
        /// </summary>
        internal static string FILE_TYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("FILE_TYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\wav.png.
        /// </summary>
        internal static string FILE_TYPE_WAV {
            get {
                return ResourceManager.GetString("FILE_TYPE_WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\.
        /// </summary>
        internal static string game_data {
            get {
                return ResourceManager.GetString("game_data", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream go_back {
            get {
                return ResourceManager.GetStream("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\HandPay.log.
        /// </summary>
        internal static string hand_pay_log {
            get {
                return ResourceManager.GetString("hand_pay_log", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\.
        /// </summary>
        internal static string machine {
            get {
                return ResourceManager.GetString("machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\machine.ini.
        /// </summary>
        internal static string machine_ini {
            get {
                return ResourceManager.GetString("machine_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\ModelManifest.ini.
        /// </summary>
        internal static string model_manifest {
            get {
                return ResourceManager.GetString("model_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\ModelManifestESP.ini.
        /// </summary>
        internal static string model_manifest_esp {
            get {
                return ResourceManager.GetString("model_manifest_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\ModelManifestB3.ini.
        /// </summary>
        internal static string model_manifest_UKB3 {
            get {
                return ResourceManager.GetString("model_manifest_UKB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\payout.dat.
        /// </summary>
        internal static string payout {
            get {
                return ResourceManager.GetString("payout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\ticket.dat.
        /// </summary>
        internal static string payout_ticket {
            get {
                return ResourceManager.GetString("payout_ticket", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream paytrans {
            get {
                return ResourceManager.GetStream("paytrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\Performance.log.
        /// </summary>
        internal static string perf_log {
            get {
                return ResourceManager.GetString("perf_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\BMP\GameIconS.png.
        /// </summary>
        internal static string PreGambleIcon {
            get {
                return ResourceManager.GetString("PreGambleIcon", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream reset {
            get {
                return ResourceManager.GetStream("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\2001\BetValues.xml.
        /// </summary>
        internal static string roulette_bet_values {
            get {
                return ResourceManager.GetString("roulette_bet_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\SecurityLog.txt.
        /// </summary>
        internal static string security_log {
            get {
                return ResourceManager.GetString("security_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\SmartCardLogFile.ini.
        /// </summary>
        internal static string smart_card_log {
            get {
                return ResourceManager.GetString("smart_card_log", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream start {
            get {
                return ResourceManager.GetStream("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\TerminalErrLog.log.
        /// </summary>
        internal static string term_error_log {
            get {
                return ResourceManager.GetString("term_error_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\TerminalWarningLog.log.
        /// </summary>
        internal static string term_warning_log {
            get {
                return ResourceManager.GetString("term_warning_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\hosts\tito_hosts.xml.
        /// </summary>
        internal static string tito_host_file {
            get {
                return ResourceManager.GetString("tito_host_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\TiTo.log.
        /// </summary>
        internal static string tito_log {
            get {
                return ResourceManager.GetString("tito_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\bmp\up.png.
        /// </summary>
        internal static string up_button {
            get {
                return ResourceManager.GetString("up_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\updatekey.txt.
        /// </summary>
        internal static string update_log {
            get {
                return ResourceManager.GetString("update_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\usb_error.log.
        /// </summary>
        internal static string usb_error_log {
            get {
                return ResourceManager.GetString("usb_error_log", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream util {
            get {
                return ResourceManager.GetStream("util", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream util_click {
            get {
                return ResourceManager.GetStream("util_click", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream util_exit {
            get {
                return ResourceManager.GetStream("util_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\1525\config\utils_config.ini.
        /// </summary>
        internal static string utils_config {
            get {
                return ResourceManager.GetString("utils_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\VizTechError.log.
        /// </summary>
        internal static string viz_tech_log {
            get {
                return ResourceManager.GetString("viz_tech_log", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream volume_snd {
            get {
                return ResourceManager.GetStream("volume_snd", resourceCulture);
            }
        }
    }
}
